version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      bash -c "/tmp/script.sh"
    ports:
      - '4200:4200'
    volumes:
      - frontend_vol:/app/data/
    restart: unless-stopped


volumes:
  frontend_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /goinfre/jmaalouf/42_transendence/frontend/ping-pong-frontend