version: '3.8'

services:
  angular:
    container_name: angular
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/dev.env
    volumes:
      # - /home/jmaalouf/Documents/42/core-curriculum/42_transendence/frontend/angular:/app-frontend
      # - /Users/jmaalouf/Documents/42_transendence/frontend/angular:/app-frontend
      # - /Users/francesco/Desktop/pong/frontend/angular:/app-frontend
      # - /Users/frmessin/Desktop/pong/frontend/angular:/app-frontend
      - /Users/ktashbae/Desktop/42_transendence/frontend/angular:/app-frontend
    ports:
      - 4200:4200
    depends_on:
      - nestjs
    restart: unless-stopped

  nestjs:
    container_name: nestjs
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      # - /home/jmaalouf/Documents/42/core-curriculum/42_transendence/backend/nest/app:/app-backend
      # - /Users/jmaalouf/Documents/42_transendence/backend/nest/app:/app-backend
      # - /Users/francesco/Desktop/pong/backend/nest/app:/app-backend
      # - /Users/frmessin/Desktop/pong/backend/nest/app:/app-backend
       - /Users/ktashbae/Desktop/42_transendence/backend/nest/app:/app-backend
    ports:
      - 3000:3000
    env_file:
      - ./backend/dev.env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:16.0-alpine3.18
    restart: unless-stopped
    volumes:
      - db-volume:/var/lib/postgresql/data
    env_file:
      - ./backend/dev.env
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:7.2.1-alpine3.18
    restart: unless-stopped
    env_file:
      - ./backend/dev.env
    volumes: 
      - redis-volume:/data
    ports:
      - 6379:6379

volumes:
  db-volume:
  redis-volume:
