version: '3.8'

services:
  angular:
    container_name: angular
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      #- /Users/jmaalouf/42_transendence/frontend/angular:/app-frontend
       - /Users/ktashbae/Desktop/trans/frontend/angular:/app-frontend
    ports:
      - 4200:4200
    depends_on:
      - nestjs
    # environment:
    #   - CHOKIDAR_USEPOLLING=true


  nestjs:
    container_name: nestjs
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      #- /Users/jmaalouf/42_transendence/backend/nest/app:/app-backend
      - /Users/ktashbae/Desktop/trans/backend/nest/app:/app-backend
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    # environment:
    #   - CHOKIDAR_USEPOLLING=true

  postgres:
    container_name: postgres
    image: postgres:16.0-alpine3.18
    restart: unless-stopped
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgresapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresDB
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:7.2.1-alpine3.18
    restart: unless-stopped
    volumes: 
      - redis-volume:/data
    ports:
      - 6379:6379

volumes:
  db-volume:
  redis-volume:
