version: '3.8'

services:
  # Frontend
  angular:
    container_name: angular
    image: node:lts
    command: bash -c "npm install && npm run start"
    volumes:
      - type: bind
        source: ./frontend/angular
        target: /app/frontend
    working_dir: /app/frontend
    ports:
      - 4200:4200
    links:
      - nestjs

  # Backend
  nestjs:
    container_name: nestjs
    image: node:lts
    command: bash -c "npm install && npm run start:dev"
    volumes:
      - type: bind
        source: ./backend/nest/app
        target: /app/backend
    working_dir: /app/backend
    depends_on:
      - postgres
    ports:
      - 3000:3000
      - 9229:9229

  # Database
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - db_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgresapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresDB
    ports:
      - 5432:5432

volumes:
  db_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/backend/db