version: '3.8'

services:
  nestjs:
    container_name: nestjs
    build:
      dockerfile: Dockerfile
      context: ./backend/nest
      target: development
    volumes:
      - ./backend/nest/app:/app/backend
    command: bash -c "npm install && npm run start:dev"
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - 3000:3000
      - 9229:9229
  angular:
    container_name: angular
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: development
    command: bash -c "npm install && npm run start"
    volumes:
      - ./frontend/angular:/app/frontend
    ports:
      - 4200:4200
    links:
      - nestjs

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: postgresapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresDB
    ports:
      - 5432:5432
