#temporell, nur fuer db

version: '3'

# volumes:
#   db_data:
#     external:
#       name: db_data

services:
  db:
    image: postgres:alpine
    env_file:
      .env
    #temp
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - transcendence

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DB_VOL} 
networks:
    transcendence:
