services:
  frontend:
    image: node:latest
    command: bash -c "npm install -g @angular/cli -y && npm install && ng serve --host=0.0.0.0"
    ports:
      - 4200:4200
    volumes:
      - type: bind
        source: ./
        target: /src
    working_dir: /src
